name: Build

on:
  push:
    branches:
      - main  # This will trigger the action on pushes to the main branch
  pull_request:
    types:
      - opened
      - synchronize
      - reopened  # This will trigger the action for pull requests when they are opened, synchronized, or reopened

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: macos-latest  # Using macOS, but you can switch to 'ubuntu-latest' if macOS is not specifically required

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disables shallow clone to ensure SonarQube understands the full git history

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set up JDK 17 for the SonarQube scanner
          distribution: 'temurin'  # Using Temurin distribution

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=nrankovic-practicals
            -Dsonar.organization=nrankovic-practicals
            -Dsonar.branch.name=${{ github.ref_name }}  # Explicitly set the branch name for the scan
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Uses the SONAR_TOKEN from your repository's secrets
