name: Build

on:
  push:
    branches:
      - main  # Ensure this matches your main branch in GitHub
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarqube:
    name: SonarQube
    runs-on: macos-latest  # or switch to ubuntu-latest if macOS is not required
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for SonarQube to understand the history for certain metrics
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set JDK version to 17
          distribution: 'temurin'  # Using Temurin as the distribution
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=nrankovic-practicals
            -Dsonar.organization=nrankovic-practicals
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
