name: Build

on:
  push:
    branches:
      - main  # This will trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Ensure PRs targeting main also trigger the action

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: macos-latest  # This is set to run on macOS, change to ubuntu-latest if not required

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for SonarQube to understand the history for certain metrics

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Ensure JDK 17 is used
          distribution: 'temurin'  # Temurin is the distribution being used

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=nrankovic-practicals
            -Dsonar.organization=nrankovic-practicals
            -Dsonar.branch.name=main  # Explicitly specifying branch name
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SONAR_TOKEN should be stored in GitHub Secrets
