name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube_scan:
    name: Build and Scan with SonarQube
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1.0.0
      with:
        args: >
          -Dsonar.projectKey=nrankovic-practicals
          -Dsonar.organization=nrankovic-practicals
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
